### ISSUE TITLE
Explicit schema on enums

### ISSUE THREAD

**Issue by lweberk** [sfackler/rust-postgres-derive#7]
Hi, 

following case;
```rust
#[derive(Debug, ToSql, FromSql)]
#[postgres(name="myschema.mood_e")]
pub enum Mood
{
    #[postgres(name="H")]
    Happy,

    #[postgres(name="S")]
    Sad,
}
```
will panic with cannot convert from/to postgresql type. Removing the `myschema` and moving the enumeration into the public schema works like a charm. Unfortunately I have the case of a DB with multiple schemas and it is kind of a bummer having to put everything into a common pool of more often than not unrelated types and enumerations.

Best Regards,
lwk

**Comment by sfackler** [comment]
Unless you have conflicting `mood_e` types in different schemas, just removing the `myschema.` should work. We should support a `schema = "myschema"` in the type-level annotation, though.

**Comment by lweberk** [comment]
Thanks. Will try and report back by tomorrow.

**Comment by lweberk** [comment]
Your solution solves this issue.
